apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-azurefiles
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: file.csi.azure.com
    volumeHandle: jenkins-dysk-001
    volumeAttributes:
      resourceGroup: rg-aks-poc-pol-001
      shareName: nfs-share
    nodeStageSecretRef:
      name: azure-storage-secret
      namespace: jenkins

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
    volumeName: jenkins-pv-azurefiles
    storageClassName: manual


