apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-azurefiles
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: file.csi.azure.com
    volumeHandle: jenkins-dysk-001
    volumeAttributes:
      resourceGroup: rg-aks-poc-pol-001
      shareName: nfs-share
      protocol: nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
    volumeName: jenkins-pv-azurefiles
    storageClassName: ""


